#------- Comment/uncomment the following line to enable/disable debugging------
DEBUG 		= n
#------------------------------------------------------------------------------

#---------------------- Change according to your files ------------------------
LIBRARY_NAME	= libvideo_vnc
SRC		=  vnc.c

CFLAGS += -I${SPXINC}/videocap

LIBS += -ldl 
include ${TOOLDIR}/rules/Rules.make.libs
#------------------------------------------------------------------------------
